# environment.yml
name: meteor-test
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.11,<3.14
  - pip
  - poetry-core
  - bowtie2>=2.3.5
  - pysam
  - pyarrow
  - pandas
  - ete4
  - packaging
  - cogent3
  - biom-format
  - py-bgzip
  - freebayes>=1.3.6